### PR TITLE
fix: allow .mjs extension for route config file

### LINKED ISSUE #12869: Allow mjs extension for route config file
### I'm using React Router as a...

framework

### Reproduction

https://stackblitz.com/edit/github-gdzzgosz

https://github.com/remix-run/react-router/blob/228b17e3e2005a33a531ac66c6722cdd7425521d/packages/react-router-dev/config/config.ts#L740

### System Info

```shell
System:
    OS: macOS 12.7.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 569.35 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 22.13.1 - ~/.local/run/fnm_multishells/1019_1737974614999/bin/node
    npm: 10.9.2 - ~/.local/run/fnm_multishells/1019_1737974614999/bin/npm
  Browsers:
    Brave Browser: 131.1.73.104
    Chrome: 131.0.6778.267
    Safari: 17.6
  npmPackages:
    @react-router/dev: 7.1.3 => 7.1.3 
    @react-router/node: 7.1.3 => 7.1.3 
    @react-router/serve: 7.1.3 => 7.1.3 
    react-router: 7.1.3 => 7.1.3 
    vite: 6.0.11 => 6.0.11
```

### Used Package Manager

npm

### Expected Behavior

`app/routes.mjs` is allowed.

### Actual Behavior

```shell
$ ls app/routes.*
app/routes.mjs
$ node --run dev
Error: Route config file not found at "app/routes.ts".
    at createConfigLoader (/tmp/test/node_modules/@react-router/dev/dist/vite.js:486:11)
    at createContext2 (/tmp/test/node_modules/@react-router/dev/dist/vite.js:775:24)
    at watch (/tmp/test/node_modules/@react-router/dev/dist/vite.js:750:15)
```

### PR DESCRIPTION
**Pull request by timdorr**
Fixes #12869

### CODE REVIEW

File: packages/react-router-dev/config/config.ts [hunk 1]
```diff
@@ -914,7 +914,7 @@ function omitRoutes(
   };
 }
 
-const entryExts = [".js", ".jsx", ".ts", ".tsx"];
+const entryExts = [".js", ".jsx", ".ts", ".tsx", ".mjs"];
```
Comment (sdavids) [inline packages/react-router-dev/config/config.ts]: While you are at it … would it make sense to add `.mts` as well?

Comment (timdorr) [reply packages/react-router-dev/config/config.ts]:
```suggestion
const entryExts = [".js", ".jsx", ".ts", ".tsx", ".mjs", ".mts"];
```
