### PR TITLE
Change useScrollRestoration to use pagehide event

### LINKED ISSUE #9463: [Bug]: Scroll Restoration not working on page refresh in mobile safari
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Scroll position is not maintained in mobile safari browsers  upon reload of a page. This is due to using  the beforeunload event which is not supported by ios safari 
```
function useBeforeUnload(callback: () => any): void {
  React.useEffect(() => {
    window.addEventListener("beforeunload", callback);
    return () => {
      window.removeEventListener("beforeunload", callback);
    };
  }, [callback]);
}
```

By changing the above code to use the visibilitychange event and checking  `document.visibilityState === 'hidden'` it seems to work as intended in safari

Reference material

https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event
https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/
https://levelup.gitconnected.com/how-to-send-an-asynchronous-request-at-the-end-of-a-page-session-90bf7229448c
https://tech.trivago.com/post/2020-11-17-exploringthepagevisibilityapifordetectin/

### Expected Behavior

Expect that when reloading a page the scroll position will be maintained in ios safari

### Actual Behavior

The scroll position goes to 0 since it  was not captured.

### PR DESCRIPTION
**Pull request by brophdawg11**
`pagehide` seems to be a better cross-browser way of detecting the unload of a page.  And in the case of scroll restoration there's no need to ever prompt the user so `pagehide` seems a better option anyway.

From https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes:

> If you're specifically trying to detect page unload events, the pagehide event is the best option.

Screenshot 2023-01-19 at 2 07 50 PM

Screenshot 2023-01-19 at 2 06 59 PM

Closes #9463

### CODE REVIEW

File: packages/react-router-dom/index.tsx [hunk 1]
```diff
@@ -1241,6 +1241,28 @@ export function useBeforeUnload(
...
 
+/**
+ * Setup a callback to be fired on the window's `pagehide` event. This is
+ * useful for saving some data to `window.localStorage` just before the page
+ * refreshes.  This event is better supported than beforeunload across browsers.
+ *
+ * Note: The `callback` argument should be a function created with
+ * `React.useCallback()`.
+ */
+function usePageHide(
```
Comment (brophdawg11) [inline packages/react-router-dom/index.tsx:1252]: Not exported currently - but if this is indeed a better way to save off some data, maybe we should export it and make a note in the docs about the use-case difference between the two hooks?

**Review by mcansh — APPROVED** [review]
