### PR TITLE
fix(useOutlet): don't wrap in ContextProvider if no child route

### LINKED ISSUE #8477: [Bug]: useOutlet() does not return `null` anymore
### What version of React Router are you using?

6.1.1

### Steps to Reproduce

This is a follow-up of https://github.com/remix-run/react-router/issues/8416. With `6.1.x`, `useOutlet()` does not return `null` anymore, even when the nested route does not render. The `OutletContext.Provider` component is always rendered.

```
function Parent() {
    const outlet = useOutlet();

    return (
        <div className={outlet ? "has-children" : "">
            {outlet}
        </div>
    )
}

function Child() {
    ....
}

function App() {
    return (
        <Routes>
            <Route path="/my/url/path" element={<Parent />}>
                <Route path=":id" element={<Child />} />
            </Route>
        </Routes>
    );
}
```

### Expected Behavior

`useOutlet()` returns `null` when the nested route does not render.

### Actual Behavior

`useOutlet()` returns `OutletContext.Provider` element.

### PR DESCRIPTION
**Pull request by mcansh**
closes #8477

### CODE REVIEW

File: packages/react-router/index.tsx [hunk 1]
```diff
@@ -579,9 +579,12 @@ export function useOutletContext<Context = unknown>(): Context {
  */
 export function useOutlet(context?: unknown): React.ReactElement | null {
   let outlet = React.useContext(RouteContext).outlet;
-  return (
-    <OutletContext.Provider value={context}>{outlet}</OutletContext.Provider>
-  );
+  if (context) {
```
Comment (mjackson) [inline packages/react-router/index.tsx:582]: I would probably use `if (outlet)` here, because `useOutlet({ some: 'context' })` without a child route should still return `null`. Does that make sense @mcansh?

**Comment by goffioul** [comment]
I'm confused by the proposed fix. Using `useOutlet(null)` (or `<Outlet context={null} />`) is still a valid use case and it doesn't mean that you don't want to provide any context to the child component, but you want to provide a null value for the context.

I could be wrong, but is there a valid use case where you'd still want to render `OutletContext.Provider` while `outlet` is `null`? It seems to me that if `outlet` is null, `useOutlet()` should just return null, whether or not a context is provided as argument.

Whether or not to wrap `outlet` with the context provider is IMO another story. I don't think you can decide solely on the `context` value, can you?

**Review by mjackson — APPROVED** [review]

**Comment by mjackson** [comment]
> It seems to me that if outlet is null, useOutlet() should just return null, whether or not a context is provided as argument.

@goffioul You are correct. This was fixed in 7d16c39
