### PR TITLE
fix: preserve state from initialEntries

### LINKED ISSUE #9265: [Bug]: MemoryRouter looses state of initial entries in v6.4.0
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

See the Sandbox at https://codesandbox.io/s/react-router-issue-9265-p8nx49 and simply downgrade `react-router-dom` to v6.3.0 to see the state value being rendered.

### Expected Behavior

MemoryRouter does not loose state of initial entries.

### Actual Behavior

MemoryRouter looses state of initial entries.

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes #9265

### CODE REVIEW

File: packages/react-router/lib/components.tsx [hunk 1]
```diff
@@ -109,16 +109,6 @@ export function RouterProvider({
   );
 }
 
-export interface DataMemoryRouterProps {
```
Comment (brophdawg11) [inline packages/react-router/lib/components.tsx:112]: Noticed this was leftover from the `DataMemoryRouter -> RouterProvider` refactor
