### PR TITLE
Fix configuring resolve conditions for Vite v6

### LINKED ISSUE #12610: Fails to resolve @prisma/client with Vite v6
### I'm using React Router as a...

framework

### Reproduction

https://github.com/silvenon/repro/tree/react-router-v7-vite-v6-resolve-prisma-client

Clone the repository:

```sh
# if you have GitHub CLI installed run
gh repo clone silvenon/repro -- --branch react-router-v7-vite-v6-resolve-prisma-client
cd repro
# otherwise run
git clone https://github.com/silvenon/repro.git
cd repro
git switch react-router-v7-vite-v6-resolve-prisma-client
```

Install dependencies and set up Prisma:

```
npm run setup
```

The issue is present both in development and in build:

```
npm run dev
```
```
npm run build
```

### System Info

```shell
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 297.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.1 - ~/.n/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.n/bin/npm
    pnpm: 9.15.1 - /opt/homebrew/bin/pnpm
    bun: 1.1.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.205
    Edge: 131.0.2903.112
    Safari: 18.2
  npmPackages:
    @react-router/dev: ^7.1.0 => 7.1.0 
    @react-router/node: ^7.1.0 => 7.1.0 
    @react-router/serve: ^7.1.0 => 7.1.0 
    react-router: ^7.1.0 => 7.1.0 
    vite: ^6.0.5 => 6.0.5
```

### Used Package Manager

npm

### Expected Behavior

Expected to be able to upgrade to React Router v7.1.0 and to Vite v6, and have my app working as usual.

### Actual Behavior

With Vite v6 it's failing to resolve `@prisma/client` both in dev and build.

Before v7.1.0 I had the same problem when I tried upgrading Vite to v6, so I was wondering what went wrong, but then I saw that you were still working on Vite v6 support so I assumed it was because of that, however unfortunately the problem remained.

I tried using Environment API to import `@prisma/client` in Vite v6 SSR without React Router involved, and it worked, so I think this has something to do with how React Router is using Vite.

```
[plugin:vite:import-analysis] Failed to resolve entry for package "@prisma/client". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@prisma/client" package
```

### PR DESCRIPTION
**Pull request by silvenon**
Configuring `resolve.conditions`/`resolve.externalConditions` in Vite v6 has changed: https://vite.dev/guide/migration.html#default-value-for-resolve-conditions

The configured conditions are no longer added to the default values, they now _replace_ the defaults. This was causing problems with resolving packages like `@prisma/client` during SSR.

This fix adds the missing default values if the default values exist, and they only exist in Vite v6, otherwise it preserves the previous behavior in order to (hopefully) maintain the same behavior with Vite v5.

Fixes #12610.

### CODE REVIEW

File: packages/react-router-dev/vite/plugin.ts [hunk 1]
```diff
@@ -804,9 +815,14 @@ export const reactRouterVitePlugin: ReactRouterVitePlugin = () => {
...
-              conditions: viteCommand === "build" ? [] : ["development"],
+              conditions:
+                viteCommand === "build"
+                  ? viteServerConditions
+                  : ["development", ...viteServerConditions],
               externalConditions:
-                viteCommand === "build" ? [] : ["development"],
+                viteCommand === "build"
+                  ? viteServerConditions
+                  : ["development", ...viteServerConditions],
```
Comment (tigerabrodi) [inline packages/react-router-dev/vite/plugin.ts:825]: I would add a comment and explain why we need this, and link to: https://vite.dev/guide/migration#default-value-for-resolve-conditions

Something like:

```
// Vite 6 no longer adds default conditions internally.
// We need to explicitly include them to ensure proper module resolution
// especially for packages that rely on specific conditions like @prisma/client
// see {link}
```

Maybe it's just me, but this code is quite critical as it handles module resolution, which is a critical part of how dependencies get loaded in the application

i would prefer being very clear here

File: packages/react-router-dev/vite/plugin.ts [hunk 2]
```diff
@@ -738,6 +738,17 @@ export const reactRouterVitePlugin: ReactRouterVitePlugin = () => {
...
+        let viteClientConditions: string[] =
+          viteUserConfig.resolve?.conditions ??
+          "defaultClientConditions" in vite
+            ? Array.from(vite.defaultClientConditions)
+            : [];
+        let viteServerConditions: string[] =
+          viteUserConfig.ssr?.resolve?.conditions ??
+          "defaultServerConditions" in vite
+            ? Array.from(vite.defaultServerConditions)
+            : [];
```
Comment (tigerabrodi) [inline packages/react-router-dev/vite/plugin.ts:750]: We could make this more type safe by specifying the literal types accepted here.

```js
type DevProdCondition = 'development' | 'production';
type BaseCondition = 'module' | DevProdCondition;

type ClientCondition = BaseCondition | 'browser';
type ServerCondition = BaseCondition | 'node' | 'workerd' | 'worker';
```

You could then use this as `ClientCondition[]` or `ServerCondition[]`.

Reading the vite docs and seeing what we have here, I think this should be fine, also helps make sure we don't mistype anything.

**Review by tigerabrodi — CHANGES_REQUESTED** [review]
I'm wondering if we should add tests?

This is critical code handling module resolution, important part how deps get loaded in the application

subtle bugs ruin it for many and cause hours of debugging 🤷 

we should cover this with tests imo

**Comment by tigerabrodi** [comment]
i think we should add a test here @silvenon 

if rr team had a test for this config in the first place, it would've been caught before shipping to production, im not entirely sure what the conventions here are etc.

i was playing around with code quickly, but the test case below should've caught the issue

i imagine it looking like:

```js
import { describe, it, expect, beforeEach } from 'vitest';

type DevProdCondition = 'development' | 'production';
type BaseCondition = 'module' | DevProdCondition;
type ServerCondition = BaseCondition | 'node' | 'workerd' | 'worker';

interface ViteConfig {
 ssr?: {
   resolve?: {
     conditions?: string[];
   }
 }
}

interface ConditionsConfig {
 vite: {
   defaultServerConditions?: string[];
 };
 userConfig?: ViteConfig;
 command: 'build' | 'serve';
}

function getServerConditions({
 vite,
 userConfig,
 command
}: ConditionsConfig): string[] {
 // Check user config first
 if (userConfig?.ssr?.resolve?.conditions !== undefined) {
   return userConfig.ssr.resolve.conditions;
 }

 // Get Vite defaults or empty array if old Vite version
 const defaultConditions = "defaultServerConditions" in vite
   ? Array.from(vite.defaultServerConditions)
   : [];

 // Add development in dev mode
 return command === 'build' 
   ? defaultConditions
   : ['development', ...defaultConditions];
}

describe('Server Conditions', () => {
 let mockVite: ConditionsConfig['vite'];
 let mockUserConfig: ViteConfig;
 
 beforeEach(() => {
   // Reset mocks before each test
   mockVite = {
     defaultServerConditions: ['module', 'node']
   };
   mockUserConfig = {};
 });

// a case like this would've caught the issue ensuring conditions isn't empty
 it('should use Vite default server conditions in build mode', () => {
   const conditions = getServerConditions({
     vite: mockVite,
     userConfig: mockUserConfig,
     command: 'build'
   });
   
   expect(conditions).toEqual(['module', 'node']);
 });
});
```

File: packages/react-router-dev/vite/plugin.ts (hunk 1 above)
Comment (silvenon) [reply packages/react-router-dev/vite/plugin.ts:829]: Good idea, I added some comments.

File: packages/react-router-dev/vite/plugin.ts (hunk 2 above)
Comment (silvenon) [reply packages/react-router-dev/vite/plugin.ts:754]: I don't see the benefit of coercing unknown strings to known strings.

**Comment by silvenon** [comment]
> i think we should add a test here

I'd like to add something, but I'd like to wait for some team feedback first, I don't really know how to test this, but thanks for your suggestion. TBH I don't know why `"development"` condition is even being added at all. I thought that Vite by default resolves to `"development"` condition during development mode and to `"production"` condition during build. Both in Vite v5 and v6.

File: packages/react-router-dev/vite/cloudflare-dev-proxy.ts [hunk 3]
```diff
@@ -43,13 +44,27 @@ export const cloudflareDevProxyVitePlugin = <Env, Cf extends CfProperties>(
...
-          externalConditions: ["workerd", "worker"],
+    config: async (userConfig) => {
+      await preloadViteEsm();
+      const vite = importViteEsmSync();
+      // a compatibility layer from Vite v6+ and below because
+      // Vite v6 overrides the default resolve.conditions, so we have to import them
+      // and if the export doesn't exist, it means that we're in Vite v5, so an empty array should be used
+      // https://vite.dev/guide/migration.html#default-value-for-resolve-conditions
+      const serverConditions =
+        userConfig.ssr?.resolve?.externalConditions ??
```
Comment (markdalgleish) [inline packages/react-router-dev/vite/cloudflare-dev-proxy.ts:55]: Merging the external conditions from the user config is new behaviour that should be considered separately from this Vite 6 fix. Can we roll this back here and in the other two places?

File: packages/react-router-dev/vite/cloudflare-dev-proxy.ts [hunk 4]
```diff
@@ -4,6 +4,7 @@ import { type Plugin } from "vite";
 import { type GetPlatformProxyOptions, type PlatformProxy } from "wrangler";
 
 import { fromNodeRequest, toNodeRequest } from "./node-adapter";
+import { preloadViteEsm, importViteEsmSync } from "./import-vite-esm-sync";
```
Comment (markdalgleish) [inline packages/react-router-dev/vite/cloudflare-dev-proxy.ts:7]: This has changed in the `dev` branch.

```suggestion
import { preloadVite, getVite } from "./vite";
```

File: packages/react-router-dev/vite/cloudflare-dev-proxy.ts (hunk 3 above)
Comment (silvenon) [reply packages/react-router-dev/vite/cloudflare-dev-proxy.ts]: Oops, indeed. Rolled back.

File: packages/react-router-dev/vite/cloudflare-dev-proxy.ts (hunk 4 above)
Comment (silvenon) [reply packages/react-router-dev/vite/cloudflare-dev-proxy.ts]: Updated.

**Comment by silvenon** [comment]
@markdalgleish done. Do you know the reason for adding the `"development"` condition in the first place? Is it for virtual modules?

**Comment by markdalgleish** [comment]
@silvenon It was added in this PR: https://github.com/remix-run/react-router/pull/12269 — but this change was later rolled back. Looks like the condition was accidentally left in, but as you pointed out, it might not have been needed in the first place. We could look at removing this in a separate PR.

File: .changeset/beige-ants-pay.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"@remix-run/router": patch
+---
+
+Fix issue with fetcher data cleanup in the data layer on fetcher unmount
```
Comment (markdalgleish) [inline .changeset/beige-ants-pay.md:5]: Your PR is targeting `main` instead of `dev`, so the merge has added a bunch of extra changes like this. Could you update the base branch for this PR?

Comment (silvenon) [reply .changeset/beige-ants-pay.md]: Oops, initially I thought I was supposed to base my PRs off of `main`, but now I know. Changed base.

File: contributors.yml [hunk 6]
```diff
@@ -47,6 +47,7 @@
 - bhbs
 - bilalk711
 - bobziroll
+- bravo-kernel
```
Comment (silvenon) [inline contributors.yml:50]: Seems like `main` and `dev` are not entirely in sync, by basing this off of `main` I'm merging this name into contributors. Should I remove it?

Comment (markdalgleish) [inline contributors.yml:50]: This change was left in.

File: docs/explanation/special-files.md [hunk 7]
```diff
@@ -248,7 +248,7 @@ export default function handleRequest(...) {
       { /* ... */ }
     );
 
-    // Abort the streaming render pass after 11 seconds soto allow the rejected
+    // Abort the streaming render pass after 11 seconds so to allow the rejected
```
Comment (markdalgleish) [inline docs/explanation/special-files.md:251]: This was accidentally included too.

File: packages/react-router-dev/vite/plugin.ts [hunk 8]
```diff
@@ -738,6 +738,19 @@ export const reactRouterVitePlugin: ReactRouterVitePlugin = () => {
         viteConfigEnv = _viteConfigEnv;
         viteCommand = viteConfigEnv.command;
 
+        // a compatibility layer from Vite v6+ and below because
+        // Vite v6 overrides the default resolve.conditions, so we have to import them
+        // and if the export doesn't exist, it means that we're in Vite v5, so an empty array should be used
+        // https://vite.dev/guide/migration.html#default-value-for-resolve-conditions
+        let viteClientConditions: string[] =
+          "defaultClientConditions" in vite
+            ? Array.from(vite.defaultClientConditions)
```
Comment (markdalgleish) [inline packages/react-router-dev/vite/plugin.ts:747]: Why is `Array.from` used here?

Comment (silvenon) [reply packages/react-router-dev/vite/plugin.ts:747]: To satisfy TypeScript, I can also do `[...vite.defaultClientConditions]`

Comment (markdalgleish) [reply packages/react-router-dev/vite/plugin.ts:747]: Could do `...vite.defaultClientConditions ?? []` (and similar in all other cases) to inline it?

File: contributors.yml (hunk 6 above)
Comment (markdalgleish) [reply contributors.yml:50]: Yep, this should be removed, and the comment change too.

Sorry, I missed this comment when replying earlier.

File: packages/react-router-dev/vite/plugin.ts (hunk 8 above)
Comment (silvenon) [reply packages/react-router-dev/vite/plugin.ts]: I've done spreading instead, shorter.

**Comment by silvenon** [comment]
I don't like rebasing, but if there's one circumstance where it's appropriate, it's when I literally based my branch off the wrong one. Here, everything clean now.

File: packages/react-router-dev/vite/plugin.ts (hunk 8 above)
Comment (silvenon) [reply packages/react-router-dev/vite/plugin.ts]: > Could do `...vite.defaultClientConditions ?? []` (and similar in all other cases) to inline it?

Ah, sorry, I didn't see this. I pushed the change now, let me know if this is what you meant.

**Review by markdalgleish — APPROVED** [review]
I've just pushed a couple of minor tweaks to finish this off.

Thanks for your work on this 🙏

**Comment by silvenon** [comment]
You're welcome, I'm very glad this got merged, thanks for your reviews!
