### PR TITLE
Ignore basename casing when matching

### LINKED ISSUE #7997: [Bug]: Basename is case sensitive
### What version of React Router are you using?

6.0.0-beta.2

### Steps to Reproduce

Create a basic router with a basename like below (or https://codesandbox.io/s/practical-waterfall-g9770?file=/src/App.js)

```js
export default function App() {
  return (
    <BrowserRouter>
      <Routes basename="/app">
        <Route path="/" element={<h1>Home page</h1>} />
      </Routes>
    </BrowserRouter>
  );
}
```

Visit `/APP`

### Expected Behavior

`/` route renders because basename matches (ignoring case), as mentioned in https://github.com/remix-run/react-router/issues/4866

### Actual Behavior

`/` route does not render

### PR DESCRIPTION
**Pull request by chaance**
Fixes #7997

### CODE REVIEW

File: packages/react-router/__tests__/Routes-test.tsx [hunk 1]
```diff
@@ -1,22 +1,37 @@
 import * as React from "react";
-import { create as createTestRenderer } from "react-test-renderer";
+import * as ReactDOM from "react-dom";
+import { act } from "react-dom/test-utils";
 import { MemoryRouter as Router, Routes, Route } from "react-router";
 
 describe("A <Routes>", () => {
+  let node: HTMLDivElement;
```
Comment (chaance) [inline packages/react-router/__tests__/Routes-test.tsx:7]: Note: I updated all of the tests in this file to use inline snapshots so its more immediately clear what each one is testing for. Personally prefer our tests that query the DOM vs. a JSON blob, but otherwise they're essentially the same!

File: packages/react-router/index.tsx [hunk 2]
```diff
@@ -718,7 +718,13 @@ export function matchRoutes(
...
-    let base = basename.replace(/^\/*/, "/").replace(/\/+$/, "");
+    let base = basename
+      // // Basename should be case-insensitive
+      // https://github.com/remix-run/react-router/issues/7997#issuecomment-911916907
+      .toLowerCase()
+      .replace(/^\/*/, "/")
+      .replace(/\/+$/, "");
+
     if (pathname.startsWith(base)) {
       pathname = pathname === base ? "/" : pathname.slice(base.length);
```
Comment (mjackson) [inline packages/react-router/index.tsx:729]: This code should probably change to something like:

```tsx
if (pathname.toLowerCase().startsWith(base)) {
  pathname = pathname.slice(base.length) || '/';
```

**Review by mjackson — CHANGES_REQUESTED** [review]
We need to lower-case the `pathname` as well, and probably add a test for weird uppercase URLs coming through to make sure they match differently-cased basenames.

File: packages/react-router/__tests__/Routes-test.tsx (hunk 1 above)
Comment (mjackson) [reply packages/react-router/__tests__/Routes-test.tsx:7]: Agree. I like inline snapshots way better than opening a separate file to check what the snapshot prints. Good call 👍
