### PR TITLE
fix: treat absolute/same-origin/different-basename <Link to> values as external

### LINKED ISSUE #10052: [Bug]: absolute redirect fails while using base url
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

- Have a react router application hosted in a sub directory e.g. `https://example.com/app1`
- `https://example.com` and `https://example.com/app1` are two independent applications. Served using a reverse proxy

`app1` is the base path and it is set using `basename`

```tsx
const router = createBrowserRouter(
  [
    {
      id: "root",
      path: "/",
      element: (
        <>
          <div>Root</div>
          <Link to="/logout">Logout</Link>
        </>
      ),
    },
    {
      path: "/logout",
      loader: LogoutLoader,
    },
  ],
  {
    basename: "app1",
  }
);
```

```tsx
export const LogoutLoader = async () => {
  return redirect("https://example.com");
};
```

- Go to logout url `https://example.com/app1/logout`

### Expected Behavior

LogoutLoader should redirect user to `https://example.com` as if it was an external redirect to somewhere like `https://google.com`. It should be a redirect via browser instead of react-router.

### Actual Behavior

React router changes the browser URL but the content of the site is still from `https://example.com/app1` instead of `https://example.com`. In the browser dev tools, no request is made to redirect URL. 

Possible bug might be here
https://github.com/remix-run/react-router/blob/6120207a328740a226c462d87be479b7c26b9574/packages/router/router.ts#L3130

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes #10052

### CODE REVIEW

File: packages/react-router-dom/__tests__/link-click-test.tsx [hunk 1]
```diff
@@ -138,7 +138,6 @@ describe("A <Link> click", () => {
           <div>
             <h1>Home</h1>
             <Link
-              reloadDocument
```
Comment (brophdawg11) [inline packages/react-router-dom/__tests__/link-click-test.tsx:141]: Shouldn't have this on this `Link` since the external URL should be what forces it to behave as a full-document link click

File: packages/react-router-dom/index.tsx [hunk 2]
```diff
@@ -434,9 +437,11 @@ export const Link = React.forwardRef<HTMLAnchorElement, LinkProps>(
...
           ? new URL(currentUrl.protocol + to)
           : new URL(to);
-        if (targetUrl.origin === currentUrl.origin) {
-          // Strip the protocol/origin for same-origin absolute URLs
-          to = targetUrl.pathname + targetUrl.search + targetUrl.hash;
+        let path = stripBasename(targetUrl.pathname, basename);
+
+        if (targetUrl.origin === currentUrl.origin && path != null) {
+          // Strip the protocol/origin/basename for same-origin absolute URLs
+          to = path + targetUrl.search + targetUrl.hash;
```
Comment (brophdawg11) [inline packages/react-router-dom/index.tsx:444]: Must have the same basename to be considered "internal" (`stripBasename` returns `null` if it doesn't).  And then we should provide the `to` without a `basename` to `useHref` which will prepend it back on

**Review by mcansh — APPROVED** [review]

**Review by jacob-ebey — APPROVED** [review]
