### PR TITLE
Fix descendant Routes rendering alongside RouterProvider errors

### LINKED ISSUE #10317: [Bug]: Nested routing (<Routes> inside <RouterProvider />)
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

**Example:**
I wrote a full example on Codesandbox for reproducing, please have a look:
https://codesandbox.io/s/react-router-v6-action-error-edbuhu?file=/src/business/business.js

image

**Explanation:**

I use `<RouterProvider />` in the root,
but I have another router inside (for my header) where I show components (search, filtering, selectors) depending on routing.
Other words inside the root "Layout" component exist a "Header" component where exist nested routes `<Routes><Route.../></Routes>`

**Steps for reproduce:**
Press the button "Submit. Press and get an error." below on the page and get an error.

To fix the problem, comment in the opened file: (business/business.js file)
`// export const APP_ENABLE_NESTED_ROUTES = true;`

**Conclusion:**
Nested routes broke errorElement handling. Why?

Thanks for your attention,
Andrii Badekha

### Expected Behavior

After pressing the button: "**Submit. Press and get an error.**",

Expect message on UI:
**`Exception properly handled in <PageError />`**

I expect that my "errorElement" will catch an error and process them, but instead, the react-router shows a general error, not my error handler component.

### Actual Behavior

After pressing the button: "**Submit. Press and get an error.**",

Get the error:
**`Error: Could not find a matching route for the current errors: [object Object]`**

As a result, my errorElement was missed, I read additionally documentation and seems like it is unexpected behaviour, docs don't cover this case.

### PR DESCRIPTION
**Pull request by brophdawg11**
Fix descendant `<Routes>` rendering inside a `RouterProvider` when data routes errors exist

Closes #10317

### CODE REVIEW

File: packages/react-router-dom/server.tsx [hunk 1]
```diff
@@ -142,6 +147,14 @@ export function StaticRouterProvider({
   );
 }
 
+function DataRoutes({
+  routes,
+}: {
+  routes: DataRouteObject[];
+}): React.ReactElement | null {
+  return useRoutes(routes);
+}
```
Comment (brophdawg11) [inline packages/react-router-dom/server.tsx:156]: This allows us to remove the fork from `<Routes>` since we can pass the routes more directly to `useRoutes` this way instead of reaching back into context

File: packages/react-router/lib/components.tsx [hunk 2]
```diff
@@ -393,15 +405,7 @@ export function Routes({
...
-  let dataRouterContext = React.useContext(DataRouterContext);
-  // When in a DataRouterContext _without_ children, we use the router routes
-  // directly.  If we have children, then we're in a descendant tree and we
-  // need to use child routes.
-  let routes =
-    dataRouterContext && !children
-      ? (dataRouterContext.router.routes as DataRouteObject[])
-      : createRoutesFromChildren(children);
-  return useRoutes(routes, location);
+  return useRoutes(createRoutesFromChildren(children), location);
```
Comment (brophdawg11) [inline packages/react-router/lib/components.tsx:408]: This is now back to only being used for non-data routers

File: packages/react-router/lib/hooks.tsx [hunk 3]
```diff
@@ -432,7 +433,10 @@ export function useRoutes(
         })
       ),
     parentMatches,
-    dataRouterStateContext || undefined
+    // Only pass along the dataRouterStateContext when we're rendering from the
+    // RouterProvider layer.  If routes is different then we're rendering from
+    // a descendant <Routes> tree
+    dataRouterContext?.router.routes === routes ? dataRouterStateContext : null
```
Comment (brophdawg11) [inline packages/react-router/lib/hooks.tsx:439]: This is the root of the bug - `_renderMatches` was behaving as if in a data router _anywhere_ under the context, including in descendant `<Routes>`.  A potentially more explicit fix would be an optional prop to `useRoutes` but I was on the fence about touching the public API:

```
export function useRoutes(
  routes: RouteObject[],
  locationArg?: Partial<Location> | string,
  isDataRouterRender?: boolean,  // New arg passed true from <DataRoutes>
)
```

**Review by jacob-ebey — APPROVED** [review]

**Comment by jasikpark** [comment]
excited to test this fix! 😄
