### PR TITLE
Fix navigation for hash routers on manual URL changes

### LINKED ISSUE #9966: [Bug]: HashRouter: browser's back button and `navigate(-1)` not work in some cases
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

1. Open https://codesandbox.io/s/react-router-6-7-0-hash-router-back-p0bztk
   - It uses `HashRouter` of react-router-dom@6.7.0.
2. Click the "Sub Page" link.
3. Press the "Back" button.

### Expected Behavior

Navigates to the root page.

### Actual Behavior

Doesn't navigate.
It isn't reproduced when using react-router-dom@6.6.2.

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes #9966

### CODE REVIEW

File: packages/router/history.ts [hunk 1]
```diff
@@ -612,24 +612,12 @@ function getUrlBasedHistory(
...
-        listener({ action, location: history.location, delta });
-      }
-    } else {
-      warning(
-        false,
-        `You are trying to perform a POP navigation to a location that was not ` +
-          `created by @remix-run/router. This will fail silently in production.  ` +
-          `You should navigate via the router to avoid this situation (instead of ` +
-          `using window.history.pushState/window.location.hash).`
-      );
```
Comment (brophdawg11) [inline packages/router/history.ts:632]: This should only apply when blockers were present, so lift it up to the router.  We'll send `delta === null` when we can't determine it

File: packages/router/router.ts [hunk 2]
```diff
@@ -781,12 +781,23 @@ export function createRouter(init: RouterInit): Router {
...
 
+        warning(
+          activeBlocker != null && delta === null,
+          "You are trying to use a blocker on a POP navigation to a location " +
+            "that was not created by @remix-run/router. This will fail silently in " +
+            "production. This can happen if you are navigating outside the router " +
+            "via `window.history.pushState`/`window.location.hash` instead of using " +
+            "router navigation APIs.  This can also happen if you are using " +
+            "createHashRouter and the user manually changes the URL."
+        );
```
Comment (brophdawg11) [inline packages/router/router.ts:792]: Warn but let the navigation apply and skip blocker logic
