### PR TITLE
Fix useNavigate when called from <Routes> inside a <RouterProvider>

### LINKED ISSUE #10430: [Bug]: useNavigate inside useRoutes broken in 6.11.0
### What version of React Router are you using?

6.11.0

### Steps to Reproduce

https://codesandbox.io/s/react-router-dom-6-11-0-si04vs

Summary:
`<Link />` inside route rendered from `useRoutes` is broken, error given indicates that `useNavigate` inside route rendered from `useRoutes` is actually broken. I'm expecting this is a bug and not incorrect usage (no matter that it's a regression since 6.10.0).

### Expected Behavior

Link renders (works in 6.10.0)

### Actual Behavior

Following error is shown:
`
Error: useNavigate can only be used on routes that contain a unique "id"
    at invariant (https://si04vs.csb.app/node_modules/@remix-run/router/dist/router.js:407:11)
    at useCurrentRouteId (https://si04vs.csb.app/node_modules/react-router/dist/index.js:761:111)
    at useNavigateStable (https://si04vs.csb.app/node_modules/react-router/dist/index.js:843:12)
    at useNavigate (https://si04vs.csb.app/node_modules/react-router/dist/index.js:468:25)
    at useLinkClickHandler (https://si04vs.csb.app/node_modules/react-router-dom/dist/index.js:925:53)
    at LinkWithRef (https://si04vs.csb.app/node_modules/react-router-dom/dist/index.js:781:25)
    at renderWithHooks (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at updateForwardRef (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19226:20)
    at beginWork (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21636:16)
    at beginWork$1 (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27426:14)
    at performUnitOfWork (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26557:12)
    at workLoopSync (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
    at renderRootSync (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
    at recoverFromConcurrentError (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (https://si04vs.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25750:22)
    at workLoop (https://si04vs.csb.app/node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (https://si04vs.csb.app/node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at performWorkUntilDeadline (https://si04vs.csb.app/node_modules/scheduler/cjs/scheduler.development.js:533:21)
    at https://codesandbox.io/static/js/vendors~react-devtools-backend.98d1f41bf.chunk.js:1:230293
    at h (https://codesandbox.io/static/js/vendors~react-devtools-backend.98d1f41bf.chunk.js:1:230408)
    at s (https://codesandbox.io/static/js/vendors~react-devtools-backend.98d1f41bf.chunk.js:1:229766)
`

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes #10430

### CODE REVIEW

File: packages/react-router/lib/hooks.tsx [hunk 1]
```diff
@@ -174,10 +174,10 @@ function useIsomorphicLayoutEffect(
  * @see https://reactrouter.com/hooks/use-navigate
  */
 export function useNavigate(): NavigateFunction {
-  let isDataRouter = React.useContext(DataRouterContext) != null;
+  let { isDataRoute } = React.useContext(RouteContext);
   // Conditional usage is OK here because the usage of a data router is static
   // eslint-disable-next-line react-hooks/rules-of-hooks
-  return isDataRouter ? useNavigateStable() : useNavigateUnstable();
+  return isDataRoute ? useNavigateStable() : useNavigateUnstable();
```
Comment (brophdawg11) [inline packages/react-router/lib/hooks.tsx:180]: We can't just look for _any_ ancestor data router context, since that gives a false positive if we're in a descendanrt routes:

```jsx
let router = createBrowserRouter([{
  path: '/*',
  Component() {
    return (
      <Routes>
        <Route path="/" element={<Home />} />
      </Routes>
    );
  }
}]);

function Home() {
  let navigate = useNavigate();
  //  ^ This should use `useNavigateUnstable` since it's the router is 
  //    unaware of the descendant routes hierarchy and cannot handle 
  //    the relative routing logic.
}

function App() {
  return <RouterProvider router={router} />
}

File: packages/react-router/lib/hooks.tsx [hunk 2]
```diff
@@ -697,7 +697,11 @@ export function _renderMatches(
       return (
         <RenderedRoute
           match={match}
-          routeContext={{ outlet, matches }}
+          routeContext={{
+            outlet,
+            matches,
+            isDataRoute: dataRouterState != null,
```
Comment (brophdawg11) [inline packages/react-router/lib/hooks.tsx:703]: In order to get route-aware "am I in a data router" we add `isDataRoute` to the `RouteContext`

**Review by jacob-ebey — APPROVED** [review]
