### PR TITLE
Fix: prendering with basename and ssr:false renders 404s for dynamic routes

### LINKED ISSUE #12083: [Bug]: v7pre - Can't use vite preview with SPA + basename + prerender
### What version of React Router are you using?

7.0.0-pre.0

### Steps to Reproduce

- Enable SPA mode (`ssr: false`)
- Set the basename to /chat/
- Enable prerender.
- Build the app with `npm run build`
- Run `vite preview`.

Minimal reproduction (run `npm run build` + `npm run preview` on it):
https://stackblitz.com/edit/react-router-v7-basename-prerender-preview?file=vite.config.ts

### Expected Behavior

When opening http://localhost:4173/chat/, the preview server responds with /build/client/chat/index.html and the root route is rendered.

### Actual Behavior

There is a 404 error response.
When opening http://localhost:4173/chat/, vite tries to respond with the file /build/client/index.html which doesn't exist (the prerendered route is in /build/client/chat/index.html), so there is a 404 response.

### PR DESCRIPTION
**Pull request by skrhlm**
Whenever `basename`  and  `ssr: false` was used together the dynamic urls in the prerender-list (which are without basename) was checked against the normalizedPath, which always has the basename included.

This resulted in that any dynamic urls are considered to become 404s in production, which is a false negative.

fixes #12083, #13615

### CODE REVIEW

File: packages/react-router/lib/server-runtime/server.ts [hunk 1]
```diff
@@ -169,14 +169,30 @@ export const createRequestHandler: CreateRequestHandlerFunction = (
...
       // Decode the URL path before checking against the prerender config
       let decodedPath = decodeURI(normalizedPath);
-      let decodedPathWithoutBasename = stripBasename(
-        normalizedPath,
-        normalizedBasename,
-      );
 
-      // handle root path
-      if (decodedPathWithoutBasename === "/") {
-        decodedPathWithoutBasename = "";
```
Comment (brophdawg11) [inline packages/react-router/lib/server-runtime/server.ts]: I don't think we needed this check because we just add the trailing slash back on below in `!_build.prerender.includes(decodedPath + "/")`

File: packages/react-router/lib/server-runtime/server.ts [hunk 2]
```diff
@@ -169,14 +169,30 @@ export const createRequestHandler: CreateRequestHandlerFunction = (
...
+              context: loadContext,
+              params,
+              request,
+            },
+          );
+          return new Response("Not Found", {
+            status: 404,
+            statusText: "Not Found",
+          });
+        }
```
Comment (brophdawg11) [inline packages/react-router/lib/server-runtime/server.ts]: If a request comes into the dev server without the basename, we can 404 to match what will happen in production

File: packages/react-router/lib/server-runtime/server.ts [hunk 3]
```diff
@@ -170,6 +170,31 @@ export const createRequestHandler: CreateRequestHandlerFunction = (
       // Decode the URL path before checking against the prerender config
       let decodedPath = decodeURI(normalizedPath);
 
+      if (normalizedBasename !== "/") {
+        let strippedPath = stripBasename(decodedPath, normalizedBasename);
+        if (strippedPath == null) {
+          // 404 on non-pre-rendered `.data` requests
```
Comment (brophdawg11) [inline packages/react-router/lib/server-runtime/server.ts]:
```suggestion
```

**Comment by brophdawg11** [comment]
🤖 bad bot - this is not in 7.8.0 and will be in the next release
