### PR TITLE
Suppress v7 warnings in production build

### LINKED ISSUE #12250: [Bug]: Too many v7 warnings
### What version of React Router are you using?

react-router-dom@6.28.0

### Steps to Reproduce

Screenshot 2024-11-08 105940

I tried 

Screenshot 2024-11-08 110115

### Expected Behavior

No warning

### Actual Behavior

Too much warnings

### PR DESCRIPTION
**Pull request by rakleed**
Closes #12250, see https://github.com/remix-run/react-router/issues/12250#issuecomment-2525223753

I prefer to use default settings and as little configuration as possible, so it is good practice to follow generally accepted standards.

I did the same as it was done in [MobX](https://github.com/mobxjs/mobx/blob/9944edcc8450fa8d328ffcc436acddd85b90e803/packages/mobx-react-lite/src/index.ts#L23) and [Antd](https://github.com/ant-design/ant-design/blob/c2efea0b336cf23d5ec74eb8a6e31743f61558a4/components/select/index.tsx#L251).

@brookslybrand

### CODE REVIEW

**Comment by rakleed** [comment]
@brookslybrand @brophdawg11 @pcattori @markdalgleish could you please review my PR?

File: packages/react-router/lib/deprecations.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ import type { FutureConfig as RenderFutureConfig } from "./components";
 const alreadyWarned: { [key: string]: boolean } = {};
 
 export function warnOnce(key: string, message: string): void {
-  if (!alreadyWarned[message]) {
+  if (process.env.NODE_ENV !== 'production' && !alreadyWarned[message]) {
```
Comment (brophdawg11) [inline packages/react-router/lib/deprecations.ts:7]: We have a build time `__DEV__` constant we can swap out for dev/prod builds to allow the library to remain runtime agnostic

```suggestion
  if (__DEV__ && !alreadyWarned[message]) {
```

**Comment by brophdawg11** [comment]
Thank you for the PR!  I'm going to merge this to my own branch so I can add a changeset and get this merged
