### PR TITLE
Fix URL creation with memory history

### LINKED ISSUE #9796: [Bug]: createMemoryRouter is dependant on Web APIs
### What version of React Router are you using?

6.6.0

### Steps to Reproduce

Create data router using `createMemoryRouter(...)` and `<RouterProvider ...>`, use redirect() or navigate() in environment that it neither test env nor a browser.

### Expected Behavior

Internal current route should change to the one provided in `redirect()` or `navigate()` (as it currently does when using `<MemoryRouter>`).

### Actual Behavior

An error is being thrown:

```
ReferenceError: window is not defined
    at createClientSideURL (/home/yiin/projects/wicked/node_modules/@remix-run/router/history.ts:570:9)
    at createClientSideRequest (/home/yiin/projects/wicked/node_modules/@remix-run/router/router.ts:2900:13)
    at startNavigation (/home/yiin/projects/wicked/node_modules/@remix-run/router/router.ts:959:19)
    at Object.navigate (/home/yiin/projects/wicked/node_modules/@remix-run/router/router.ts:859:18)
```

### PR DESCRIPTION
**Pull request by brophdawg11**
Fixing an oversight from https://github.com/remix-run/react-router/pull/9682/files#r1040159998.  Now `URL` creation is driven by `history.createURL` so we have clear boundaries between memory versus browser cases.

Closes #9796

### CODE REVIEW

File: packages/router/__tests__/browser-test.ts [hunk 1]
```diff
@@ -1,7 +1,3 @@
-/**
- * @jest-environment ./__tests__/custom-environment.js
```
Comment (brophdawg11) [inline packages/router/__tests__/browser-test.ts:2]: Unsure why we had 2 ways of doing this but I moved the custom environment stuff into `setup.ts`

File: packages/router/__tests__/router-memory-test.ts [hunk 2]
```diff
@@ -0,0 +1,107 @@
+/**
+ * @jest-environment node
+ */
```
Comment (brophdawg11) [inline packages/router/__tests__/router-memory-test.ts:3]: Because tests by default run in jsdom, we didn't catch this regression since `window` was defined during test runs when using a memory history.  Now we have this standalone file that runs directly in node to catch those

File: packages/router/__tests__/setup.ts [hunk 3]
```diff
@@ -13,3 +18,14 @@ if (!globalThis.fetch) {
   // @ts-expect-error
   globalThis.Response = Response;
 }
+
+if (!globalThis.AbortController) {
+  // @ts-expect-error
+  globalThis.AbortController = NodeAbortController;
```
Comment (brophdawg11) [inline packages/router/__tests__/setup.ts:24]: Needed for the new node test run

File: packages/router/__tests__/setup.ts [hunk 4]
```diff
@@ -13,3 +18,14 @@ if (!globalThis.fetch) {
...
+}
+
+if (!globalThis.TextEncoder || !globalThis.TextDecoder) {
+  globalThis.TextEncoder = NodeTextEncoder;
+  // @ts-expect-error
+  globalThis.TextDecoder = NodeTextDecoder;
+}
```
Comment (brophdawg11) [inline packages/router/__tests__/setup.ts:31]: Copied over from the deleted custom environment

File: packages/router/router.ts [hunk 5]
```diff
@@ -1719,7 +1728,7 @@ export function createRouter(init: RouterInit): Router {
 
     // Check if this an external redirect that goes to a new origin
     if (typeof window?.location !== "undefined") {
-      let newOrigin = createClientSideURL(redirect.location).origin;
+      let newOrigin = init.history.createURL(redirect.location).origin;
```
Comment (brophdawg11) [inline packages/router/router.ts:1731]: All (non-static-handler) URL creation now uses the `history.createURL` function

File: packages/router/history.ts [hunk 6]
```diff
@@ -265,8 +276,9 @@ export function createMemoryHistory(
     get location() {
       return getCurrentLocation();
     },
-    createHref(to) {
-      return typeof to === "string" ? to : createPath(to);
+    createHref,
+    createURL(to) {
+      return new URL(createHref(to), "http://localhost");
```
Comment (brophdawg11) [inline packages/router/history.ts:281]: memory histories will use localhost as the URL base

**Review by jacob-ebey — APPROVED** [review]
