### PR TITLE
fix: pass nonce to importmap script when using subResourceIntegrity

### LINKED ISSUE #14252: Subresource Integrity (unstable), nonce and CSP
### Reproduction

1. Go to https://codesandbox.io/p/devbox/lkj4ys
2. Click on "Preview:3000" or run `npm run build` and `npm run start`
3. Inspect code (`<script>` tags)

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 2.33 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @react-router/dev: ^7.8.2 => 7.8.2 
    @react-router/node: ^7.8.2 => 7.8.2 
    @react-router/serve: ^7.8.2 => 7.8.2 
    react-router: ^7.8.2 => 7.8.2 
    vite: ^7.1.3 => 7.1.3
```

### Used Package Manager

npm

### Expected Behavior

`<script rr-importmap type="importmap">` tag to have a `nonce` attribute with a value of "123"

### Actual Behavior

`<script rr-importmap type="importmap">` tag doesn't have a `nonce` attribute and would be blocked if a respective `Content-Security-Policy` header (without `unsafe-inline`) would be used (not used in this demo).

Image

_Note_: This is **not** a demonstration of how to use a `nonce` in React Router. The `nonce` value should not be hard coded like shown in this demo and should not be exposed to the client.

### PR DESCRIPTION
**Pull request by dimmageiras**
## Description

When `unstable_subResourceIntegrity` is enabled, the importmap script tag was missing the `nonce` attribute, causing CSP violations when strict Content Security Policy is enforced without `'unsafe-inline'`.

This fix ensures the `nonce` attribute is properly passed to the importmap script element, allowing applications to use strict CSP policies.

## Changes

- **packages/react-router/lib/dom/ssr/components.tsx**: Added `nonce={scriptProps.nonce}` to the importmap script element

## Impact

- Fixes CSP compatibility issue with subResourceIntegrity feature
- Allows applications to use strict CSP policies without `unsafe-inline`
- No breaking changes - only adds missing nonce attribute

Fixes #14252

### CODE REVIEW

File: packages/react-router/lib/dom/ssr/components.tsx [hunk 1]
```diff
@@ -903,6 +903,7 @@ import(${JSON.stringify(manifest.entry.module)});`;
         <script
           rr-importmap=""
           type="importmap"
+          nonce={scriptProps.nonce}
```
Comment (brophdawg11) [inline packages/react-router/lib/dom/ssr/components.tsx]: This should probably be `<script {...scriptProps} ...>` like we do on the `<script>` tags above?

**Comment by brophdawg11** [comment]
Thanks!  Can you add a [changeset](https://github.com/remix-run/react-router/pull/14675#issuecomment-3674484635) file to the branch via `pnpm changeset`?

File: packages/react-router/lib/dom/ssr/components.tsx (hunk 1 above)
Comment (dimmageiras) [reply packages/react-router/lib/dom/ssr/components.tsx]: done

**Comment by dimmageiras** [comment]
> Thanks! Can you add a [changeset](https://github.com/remix-run/react-router/pull/14675#issuecomment-3674484635) file to the branch via `pnpm changeset`?

I hope I did it properly

File: .changeset/little-timers-occur.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"react-router": patch
+---
+
+This fix ensures nonce prop to be passed to the script component
```
Comment (brophdawg11) [inline .changeset/little-timers-occur.md]:
```suggestion
[UNSTABLE] Pass `<Scripts nonce>` value through to the underlying `importmap` `script` tag when using `future.unstable_subResourceIntegrity`
