### PR TITLE
Fix double slash normalization for `useNavigate` paths with colons

### LINKED ISSUE #14711: v7.9.6 Breaking Change: When using a colon in navigation, must precede relative paths with `./`
### Reproduction

1. Navigate to https://stackblitz.com/edit/github-chzf5vkt
2. Click "Broken" (routing error occurs)
3. Refresh Stackblitz app
4. Click "Not Broken" (no routing error)

### System Info
Note that while the following are what I'm running on my local machine, this bug is reproducible with any version of react-route at or above v7.9.6 (using react 18 or 19).

```shell
System:
  OS: macOS 26.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 275.95 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 22.18.0
  npm: 11.5.2
  bun: 1.3.5
  Watchman: 2025.12.15.00
Browsers:
  Chrome: 143.0.7499.171
  Safari: 26.1
npmPackages:
  react-router: 7.9.6 => 7.9.6 
  vite: ^7.3.0 => 7.3.1
```

### Used Package Manager

bun/npm

### Expected Behavior

When calling `navigate({ pathname: 'my-path:with-colon' }, { replace: true });`, RR should navigate to that path relative to the current location (versions prior to 7.9.6 allowed this)

### Actual Behavior

When calling `navigate({ pathname: 'my-path:with-colon' }, { replace: true });`, RR errors.
Must use `navigate({ pathname: './my-path:with-colon' }, { replace: true });` to fix.

When running on my machine, I get:
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'my-path:with-colon' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/';
```
When running in stackblitz, I seem to get:
```
No routes matched location "with-colon" 
```
Unsure of why they are different, though locally my app is only client-side with Declarative routing, and the example is server side with framework routing.

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes https://github.com/remix-run/react-router/issues/14711

This is a rework of the solution from https://github.com/remix-run/react-router/pull/14529 that removes the absolute path check because `resolvePath` doesn't need to handle absolute URLs.

### CODE REVIEW

File: packages/react-router/lib/router/utils.ts [hunk 1]
```diff
@@ -1603,23 +1603,11 @@ export function resolvePath(to: To, fromPathname = "/"): Path {
 
   let pathname: string;
   if (toPathname) {
-    if (isAbsoluteUrl(toPathname)) {
-      pathname = toPathname;
+    toPathname = toPathname.replace(/\/\/+/g, "/");
```
Comment (brophdawg11) [inline packages/react-router/lib/router/utils.ts:1606]: We didn't need to be checking for absolute URLs at all here before.  `resolvePath` is only intended to manage pathnames/search/hash - absolute navigations are handled outside of here by `Link` so we can just always do the double slash replacement here.

Comment (onixmahmoudi) [reply packages/react-router/lib/router/utils.ts:1606]: is it intended that `navigate("https://<absolute path>")` doesn't work now? because it used to work before this change and it was a breaking change for us.

Comment (vincerubinetti) [reply packages/react-router/lib/router/utils.ts:1606]: Same, this was surprising, especially since it's not mentioned anywhere in the changelog or docs.

To be clear, I think it makes sense that it wouldn't handle absolute links. But this is definitely a breaking change that should've been noted somewhere.
