### PR TITLE
Fix pathless relative routing with a basename

### LINKED ISSUE #10431: [Bug]: Basename is duplicated when calling `setSearchParams`
### What version of React Router are you using?

6.11.0

### Steps to Reproduce

1. Start a React app using this code:
```typescript
import { useEffect } from "react";
import ReactDOM from "react-dom/client";
import { Route, RouterProvider, createBrowserRouter, createRoutesFromElements, useSearchParams } from "react-router-dom";

const Foo = () => {
  const [_, setSearchParams] = useSearchParams();

  useEffect(() => {
    setSearchParams({
      bar: "baz",
    });
  }, [setSearchParams]);

  return null;
};

const router = createBrowserRouter(
  createRoutesFromElements(<Route path="/foo" element={<Foo />} />),
  { basename: "/base" }
);

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <RouterProvider router={router} />
);
```
2. Configure your server to serve the app from `/base`, e.g. with this Vite config:
```typescript
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    base: "/base",
  },
});
```
3. Open `/base/foo` in your browser, e.g. with the default Vite port: http://127.0.0.1:5173/base/foo

### Expected Behavior

The app should redirect to http://127.0.0.1:5173/base/foo?bar=baz

This is what happens with `react-router-dom@6.10.0`.

### Actual Behavior

The app redirects to http://127.0.0.1:5173/base/base/foo?bar=baz

I.e. the `/base` part is duplicated. In React's strict mode, when everything is rendered twice in development, it even redirects to http://127.0.0.1:5173/base/base/base/foo?bar=baz

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes #10431

### CODE REVIEW

File: packages/router/router.ts [hunk 1]
```diff
@@ -3094,7 +3094,7 @@ function normalizeTo(
   let path = resolveTo(
     to ? to : ".",
     getPathContributingMatches(contextualMatches).map((m) => m.pathnameBase),
-    location.pathname,
+    stripBasename(location.pathname, basename) || location.pathname,
```
Comment (brophdawg11) [inline packages/router/router.ts:3097]: `useLocation` strips this off so this code brought in from the react layer lost that since the raw router location contains the basename

**Comment by soolx** [comment]
Basename is duplicated when calling useNavigate using 6.11.1, but 6.11.0 is work fine

**Comment by brophdawg11** [comment]
Fixed by https://github.com/remix-run/react-router/pull/10492 - available in `6.11.2-pre.0` currently and should have a stable out this week
