### PR TITLE
fix: relative navigation from index/pathless routes

### LINKED ISSUE #8350: [Bug]:  Relative navigation issue while navigating from "index" route: ".." doesn't works, I must use "../.." to go back
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

```
<Some other routes>
....
<Route path='/pages'>
    <Route index element={<Pages />} />

    <Route path=':pageId' element={<Item />} />              
  </Route>
  
```
  
  Navigation via '..' from Pages with "index" doesn't works but it is ok for Item
  I should use '../..' for the same result as '..'

### Expected Behavior

Should navigate level up via '..' from index route
And it would be nice to have option with nested routes that is used only to create url hierarchy for relative navigation usage, but without children and parrents ui rendering

### Actual Behavior

doesnt navigate from index page via '..'

### PR DESCRIPTION
**Pull request by brophdawg11**
Continuation of https://github.com/remix-run/react-router/pull/8697

Closes #8350

### CODE REVIEW

File: packages/react-router/__tests__/navigate-test.tsx [hunk 1]
```diff
@@ -45,5 +45,152 @@ describe("<Navigate>", () => {
...
+        renderer = TestRenderer.create(
+          <MemoryRouter initialEntries={["/home/page"]}>
+            <Routes>
+              <Route path="home" element={<Outlet />}>
+                <Route element={<Outlet />}>
+                  <Route element={<Outlet />}>
+                    <Route element={<Outlet />}>
+                      <Route
+                        path="page"
+                        element={<Navigate to="../../about" />}
```
Comment (brophdawg11) [inline packages/react-router/__tests__/navigate-test.tsx:133]: @ryanflorence Quick double check here that this double `../..` would be the expected relative path to the `/about` route?
