### PR TITLE
Provide fetcher submission to shouldRevalidate if fetcher action redirects

### LINKED ISSUE #10176: [Bug]: shouldRevalidate missing FormData if action called by fetcher.submit returns (or throws) a redirect.
### What version of React Router are you using?

v6.8.2

### Steps to Reproduce

- Create action that throws a redirect.
- Send "POST" to that action using `fether.submit`
- Notice that `shouldRevalidate` is called but it does not include the formData that was originally sent. 

### Expected Behavior

- I would expect that I would still have access to the formData that caused the redirect.

### Actual Behavior

- `formData` and `formMethod` are both undefined when action throws redirect.

> As a side note, `useSubmit` works as expected.

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes #10176

### CODE REVIEW

File: packages/router/__tests__/router-test.ts [hunk 1]
```diff
@@ -1825,12 +1833,12 @@ describe("a router", () => {
       expect(rootLoader.mock.calls.length).toBe(1);
       expect(shouldRevalidate.mock.calls[0][0]).toMatchObject({
         currentParams: {},
-        currentUrl: new URL("http://localhost/child"),
+        currentUrl: expect.URL("http://localhost/child"),
```
Comment (brophdawg11) [inline packages/router/__tests__/router-test.ts:1836]: Found out that `new URL` inside `toMatchObject` doesn't actually validate the internal URL 🤦 , so added the custom matcher and changed all existing instances.  Thankfully no false positives.

File: packages/router/__tests__/router-test.ts [hunk 2]
```diff
@@ -2269,6 +2277,10 @@ describe("a router", () => {
           "currentParams": {},
           "currentUrl": "http://localhost/",
           "defaultShouldRevalidate": true,
+          "formAction": "/fetch",
+          "formData": FormData {},
+          "formEncType": "application/x-www-form-urlencoded",
+          "formMethod": "post",
```
Comment (brophdawg11) [inline packages/router/__tests__/router-test.ts:2283]: Fetcher submission should be included to `shouldRevalidate` if the fetcher `action` redirected

**Review by mcansh — APPROVED** [review]
